name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'
  schedule:
    - cron: '0 */6 * * *'  # Jalankan setiap 6 jam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone runbot repository
      run: |
        git clone https://github.com/AP-update/runbot.git

    # Step 2: Install unzip tool
    - name: Install unzip tool
      run: sudo apt-get install unzip -y

    # Step 3: Unzip lenwygit.zip file inside the runbot folder
    - name: Unzip lenwygit.zip
      run: |
        unzip runbot/lenwygit.zip -d ./runbot

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd runbot
        npm install

    # Step 5: Install pm2 for process management
    - name: Install PM2
      run: npm install -g pm2

    # Step 6: Start the application using PM2
    - name: Start the application with PM2
      run: |
        cd runbot
        pm2 start npm --name "runbot" -- start

    # Step 7: Save PM2 process list for restart
    - name: Save PM2 process list
      run: pm2 save
