name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'
  schedule:
    - cron: '0 */6 * * *'  # Jalankan setiap 6 jam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone runbot repository
      run: |
        git clone https://github.com/AP-update/runbot.git || echo "Clone failed, continuing..."
      continue-on-error: true  # Toleransi jika terjadi error pada langkah ini

    # Step 2: Navigate into the runbot directory
    - name: Change directory to runbot
      run: cd runbot || echo "Directory not found, continuing..."
      continue-on-error: true  # Toleransi jika terjadi error pada langkah ini

    # Step 3: Unzip lenwygit.zip file inside the runbot folder
    - name: Unzip lenwygit.zip
      run: |
        sudo apt-get install unzip -y || echo "Unzip tool installation failed, continuing..."
        unzip runbot/lenwygit.zip -d ./runbot || echo "Unzip failed, continuing..."
      continue-on-error: true  # Toleransi jika terjadi error pada langkah ini

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd runbot || echo "Cannot change to runbot directory, continuing..."
        npm install || echo "NPM install failed, continuing..."
      continue-on-error: true  # Toleransi jika terjadi error pada langkah ini

    # Step 5: Start the npm application
    - name: Start the application
      run: |
        cd runbot || echo "Cannot change to runbot directory, continuing..."
        npm start || echo "Application start failed, continuing..."
      continue-on-error: true  # Toleransi jika terjadi error pada langkah ini
